### ISSUE TITLE
RoadMap of Upcoming Features and Updates

### ISSUE THREAD

**Issue by iamDyeus** [iamDyeus/KnickAI#43]
# Tasks To Do  :

- [ ] Remove all the Unnecessary .mp3 ( `introduction.mp3` , etc)
- [ ] Use TTS, instead of Pre-Recorded Reply's
- [x] Goodbye ViewBot, Google Trends. Remove Both of these Extended Features
- [ ] Remove Unnecessary Terminal Text Formatting.
- [ ] Remove Useless BOOT Introduction. ( `startup.py` )
- [ ] Improving the Communication between user and the Bot.
- [ ] Use of Classes and Arrays instead of the Current if-else logic.
- [ ] Feature : Addition of Home Automation Features
- [ ] Feature : Automatic Reply to Email's As Well As WhatsApp Messages.
